version: '3.8'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bidb"
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql